export const Users = [
    {
      id:1,
      profilePicture: "person/1.jpeg",
      username: "Spyt Chrysotom",
    },
    {
      id:2,
      profilePicture: "person/2.jpeg",
      username: "Ebube Priest",
    },
    {
      id:3,
      profilePicture: "person/3.jpeg",
      username: "Favor Spice",
    },
    {
      id:4,
      profilePicture: "person/4.jpeg",
      username: "Nooni Nicon",
    },
    {
      id:5,
      profilePicture: "person/5.jpeg",
      username: "Didiv Rose",
    },
    {
      id:6,
      profilePicture: "person/6.jpeg",
      username: "Mike Memor",
    },
    {
      id:7,
      profilePicture: "person/7.jpeg",
      username: "Festus Law",
    },
    {
      id:8,
      profilePicture: "person/8.jpeg",
      username: "Sweet White",
    },
    {
      id:9,
      profilePicture: "person/9.jpeg",
      username: "Jasper Chid",
    },
    {
      id:10,
      profilePicture: "person/10.jpeg",
      username: "Lucia Kamaru",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/1.jpeg",
      date: "3 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/2.jpeg",
      date: "12 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "In hoc signo vinces",
      photo: "post/3.jpeg",
      date: "5 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/4.jpeg",
      date: "1 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc: "Life is crazily random",
      photo: "post/5.jpeg",
      date: "3 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/6.jpeg",
      date: "3 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Sandra's rose.",
      photo: "post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpeg",
      date: "4 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Be still, be formless, jus like water",
      photo: "post/9.jpeg",
      date: "10 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  